kind: pipeline
type: docker
name: fluxo-bi-ui-pipeline

trigger:
  branch: [main]
  event: [push]

steps:
  - name: install-and-test
    image: node:20-alpine
    commands:
      - npm ci

  - name: build-and-publish
    image: plugins/docker
    settings:
      dockerfile: Dockerfile
      registry: docker.io
      repo: k3rb3rdock/fluxo-bi-ui
      tags:
        - ${DRONE_COMMIT_SHA:0:8} # Usar um tag único é melhor que 'latest'
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password


  - name: deploy-to-k8s
    image: alpine/k8s:1.29.2
    environment:
      KUBE_CONFIG:
        from_secret: kube_config
    commands:
      - mkdir -p ~/.kube
      - echo "$KUBE_CONFIG" > ~/.kube/config
      - kubectl set image deployment/fluxo-bi-ui-deployment fluxo-bi-ui-container=k3rb3rdock/fluxo-bi-ui:${DRONE_COMMIT_SHA:0:8} -n dev
      - kubectl rollout status deployment/fluxo-bi-ui-deployment -n dev  # Aguarda deploy
