apiVersion: v1
kind: Service
metadata:
  name: fluxo-bi-ui-service
spec:
  type: NodePort
  selector:
    app: fluxo-bi-ui
  ports:
    - protocol: TCP
      port: 80         # Porto interno do serviço no cluster
      targetPort: 80   # Porto onde o container está a ouvir (o Nginx)
      nodePort: 30133  # Porto que será aberto no nosso nó K3s
